[[actions]]
name = "new-main"
lua = '''
jj_async("new", "dev@origin")
revisions.refresh()
'''

[[bindings]]
action = "new-main"
seq = ["x", "n"]
scope = "revisions"
desc = "new revision based on main"

[[actions]]
name = "resolve"
lua = '''
jj_async("resolve", "-r", context.change_id())
revisions.refresh()
'''

[[bindings]]
action = "resolve"
seq = ["x", "r"]
scope = "revisions"
desc = "Resolve a revision"

[ui.tracer]
enabled = true
